package migrate

import (
	"fmt"
	"path/filepath"
	"strings"
)

// The reports are the human review surface of a migration run. They are plain Markdown, deterministic, and never
// contain a secret value: only the state path a value has to be copied from.

func readme(m *Manifest, opts Options) string {
	out := &strings.Builder{}
	section(out, "Descope project split migration")
	line(out, "Generated by %s for %s.", ToolName, m.LegacyAddress)
	blank(out)
	line(out, "Terraform cannot fan one resource's state into several destination resources: `UpgradeState`, `MoveState`")
	line(out, "and `moved` blocks all map one prior instance onto one new instance. This migration therefore adopts the")
	line(out, "existing objects natively: the legacy `%s` is detached from state without deleting anything remotely, and", ProjectResourceType)
	line(out, "every destination is then adopted with an `import` block and reconciled with a non-destructive plan.")
	blank(out)
	line(out, "- project: `%s`", m.ProjectID)
	line(out, "- legacy address: `%s`", m.LegacyAddress)
	line(out, "- module: `%s`", moduleLabel(m))
	line(out, "- destinations: %d", len(m.Entries))
	line(out, "- source provider: `%s` `%s`", m.SourceProvider.Source, m.SourceProvider.Version)
	line(out, "- target provider: `%s` `%s`", m.TargetProvider.Source, m.TargetProvider.Version)
	line(out, "- Terraform: `%s`; 1.7 introduced the migration blocks and 1.8 adds the plan completeness signal `verify-plan` requires", m.RequiredTerraform)
	line(out, "- ownership: %s", m.OwnershipPolicy)
	if opts.Remote {
		line(out, "- ids were allowed to be backfilled with GET-only reads of the project")
	}
	if m.InputFormat == formatShowJSON {
		line(out, "- WARNING: Terraform show JSON does not identify provider aliases. Confirm that the module's default")
		line(out, "  `descope` provider is the same configuration that owned the legacy resource before adoption.")
	}
	blank(out)

	section(out, "File placement")
	line(out, "| file | goes in |")
	line(out, "| --- | --- |")
	line(out, "| `%s` | the module that declares `%s` |", filepath.Join(detachDir, "removed.tf"), m.LegacyLocalAddr)
	line(out, "| `%s` | the module that declares `%s` |", filepath.Join(detachDir, "versions.tf"), m.LegacyLocalAddr)
	line(out, "| `%s` | the module that declares `%s` |", filepath.Join(adoptDir, "main.tf"), m.LegacyLocalAddr)
	line(out, "| `%s` | the module that declares `%s` |", filepath.Join(adoptDir, "variables.tf"), m.LegacyLocalAddr)
	line(out, "| `%s` | the module whose provider version is being upgraded, normally the root module |", filepath.Join(adoptDir, "versions.tf"))
	line(out, "| `%s` | the root module: `import` blocks are only evaluated there |", filepath.Join(adoptDir, "imports.tf"))
	line(out, "| `%s/` | next to `main.tf`, referenced with `file(\"${path.module}/...\")` |", filepath.Join(adoptDir, payloadDir))
	blank(out)
	line(out, "Generated payload files can contain customer configuration and must be reviewed and protected as sensitive material.")
	blank(out)

	section(out, "Stage 1: detach, with the source provider still pinned")
	line(out, "1. Freeze the Terraform workspace, every apply pipeline and Descope console edits for this project.")
	if m.Rollback.Restorable {
		line(out, "2. SENSITIVE: keep `%s` somewhere secret. It is a raw state backup and contains credentials.", m.Rollback.StateBackup)
	} else {
		line(out, "2. SENSITIVE: `%s` is a Terraform show snapshot, not a restorable state backup.", m.Rollback.StateBackup)
		line(out, "   Before detach, capture raw state with `(umask 077; set -o noclobber; terraform state pull > legacy.tfstate.json)`.")
	}
	line(out, "3. Before removing the declaration, find every Terraform expression that references `%s`.", m.LegacyLocalAddr)
	line(out, "   Temporarily replace `.id` uses with the captured HCL string `\"%s\"`; preserve module outputs by changing", m.ProjectID)
	line(out, "   their values rather than deleting them. Replace uses of other project attributes with their exact preserved")
	line(out, "   values. Run `terraform validate`, and do not detach while any reference to `%s` remains.", m.LegacyLocalAddr)
	line(out, "4. Preserve the legacy HCL for review, remove its `resource` block from the module, and put `%s` in its place.", filepath.Join(detachDir, "removed.tf"))
	line(out, "5. Run `terraform plan`. The only change must be the single expected `forget` of `%s`.", m.LegacyAddress)
	line(out, "6. Have a human approve that plan, then `terraform apply`.")
	blank(out)
	line(out, "`removed` with `lifecycle { destroy = false }` drops the resource from state only. No Descope object is deleted,")
	line(out, "and nothing about the project changes remotely.")
	blank(out)

	section(out, "Stage 2: adopt, with the target provider pinned")
	line(out, "1. Remove `%s`. Copy `%s`, `%s` and `%s/` into the module, and `%s` into the root module.",
		filepath.Join(detachDir, "removed.tf"), filepath.Join(adoptDir, "main.tf"), filepath.Join(adoptDir, "variables.tf"), filepath.Join(adoptDir, payloadDir), filepath.Join(adoptDir, "imports.tf"))
	line(out, "2. Pin the provider to `%s` and run `terraform init -upgrade`.", m.TargetProvider.Version)
	line(out, "3. Supply every variable in `%s` from your own secret store, including all required parent-module inputs.", secretsPath)
	line(out, "4. Reconnect temporary literals for retained core attributes (`id`, `name`, `environment`, `tags` and")
	line(out, "   `deletion_protection`) to `%s`. Reconnect each removed nested attribute through the", m.LegacyLocalAddr)
	line(out, "   `manifest.json` entry whose `legacy_path` owns it, using that entry's standalone `address`; never reconnect")
	line(out, "   a removed nested attribute to `%s`. Preserve every original module output contract.", m.LegacyLocalAddr)
	line(out, "5. Run `terraform validate`. Do not continue until provider initialization, module inputs and references are valid.")
	line(out, "6. Run `(umask 077; terraform plan -out=adopt.tfplan)` and then")
	line(out, "   `(umask 077; set -o noclobber; terraform show -json adopt.tfplan > adopt-plan.json)`. Both files")
	line(out, "   contain sensitive values: never commit or upload them, and delete them according to your retention policy.")
	line(out, "7. Verify the plan is non-destructive. Set `MIGRATION_OUTPUT` to the exact directory passed to `plan -out`:")
	blank(out)
	line(out, "        MIGRATION_OUTPUT=\"<migration-output>\"")
	line(out, "        go run github.com/descope/terraform-provider-descope/tools/tfmigrate@v%s verify-plan -plan adopt-plan.json -manifest \"$MIGRATION_OUTPUT/%s\"", m.TargetProvider.Version, manifestPath)
	blank(out)
	line(out, "8. Only after verification passes, have a human approve and `terraform apply`.")
	blank(out)

	section(out, "What the adoption plan is allowed to contain")
	line(out, "- `no-op` with an import: the adopted resources.")
	line(out, "- `no-op` without an import: resources that were already converged.")
	line(out, "- `update` with an import, touching only the secret attributes the manifest enumerates.")
	blank(out)
	line(out, "The last case is unavoidable rather than optional: the Descope API never returns a stored secret, so a")
	line(out, "freshly imported resource holds `null` for it while the configuration holds the required value. The update")
	line(out, "writes the same value back and changes nothing else. Any other action fails verification.")
	blank(out)

	if len(m.Standalone) > 0 {
		section(out, "Already standalone")
		line(out, "These resources already have their own Terraform state and are not imported or declared again:")
		blank(out)
		for _, standalone := range m.Standalone {
			line(out, "- `%s` (`%s`, backend id `%s`): %s", standalone.Address, standalone.Type, standalone.BackendID, standalone.Detail)
		}
		blank(out)
	}

	if len(m.Unowned) > 0 {
		section(out, "Not adopted")
		for _, unowned := range m.Unowned {
			line(out, "- `%s`: %s", unowned.LegacyPath, unowned.Detail)
		}
		blank(out)
	}

	section(out, "Still owned by descope_project")
	for _, retained := range m.Retained {
		line(out, "- `%s`: %s", retained.Attribute, retained.Detail)
	}
	blank(out)
	line(out, "Rollback material is described in `%s`. The utility never rolls back and never mutates state.", rollbackPath)
	return out.String()
}

func blockedReadme(m *Manifest) string {
	out := &strings.Builder{}
	section(out, "Descope project split migration: blocked")
	line(out, "The migration of `%s` is not safe to run, so no detach or adopt configuration was generated.", m.LegacyAddress)
	blank(out)
	line(out, "%d blocker(s) are listed in `%s`, and the full machine readable inventory is in `%s`.", len(m.Blockers), blockersPath, manifestPath)
	line(out, "Resolve every blocker and rerun. Never invent an id or a secret to clear one: the migration would then")
	line(out, "adopt the wrong object or write the wrong credential.")
	blank(out)
	line(out, "`%s` is still written as a protected copy of the supplied input; see `%s` for whether it is restorable.", m.Rollback.StateBackup, rollbackPath)
	return out.String()
}

func blockerReport(m *Manifest) string {
	out := &strings.Builder{}
	section(out, "Blockers")
	line(out, "Each entry stops the migration. The utility fails closed rather than emitting a partial migration.")
	blank(out)
	if len(m.Standalone) > 0 {
		section(out, "Already standalone")
		line(out, "These resources already have their own Terraform state and are not imported or declared again:")
		blank(out)
		for _, standalone := range m.Standalone {
			line(out, "- `%s` (`%s`, backend id `%s`): %s", standalone.Address, standalone.Type, standalone.BackendID, standalone.Detail)
		}
		blank(out)
	}

	for _, kind := range blockerKindOrder {
		matching := []Blocker{}
		for _, blocker := range m.Blockers {
			if blocker.Kind == kind {
				matching = append(matching, blocker)
			}
		}
		if len(matching) == 0 {
			continue
		}
		section2(out, kind)
		line(out, "%s", blockerKindHelp[kind])
		blank(out)
		for _, blocker := range matching {
			target := blocker.LegacyPath
			if blocker.Address != "" {
				target = fmt.Sprintf("%s -> %s", blocker.LegacyPath, blocker.Address)
			}
			line(out, "- `%s`: %s", target, blocker.Detail)
		}
		blank(out)
	}
	return out.String()
}

// blockerKindOrder fixes the report order so a rerun produces the same document.
var blockerKindOrder = []string{
	BlockerMissingID,
	BlockerUnresolvedSecret,
	BlockerUnresolvedRef,
	BlockerMissingPayload,
	BlockerUnsupportedField,
	BlockerUnknownAttribute,
	BlockerDuplicateAddress,
	BlockerAmbiguousOwnership,
	BlockerInvalidValue,
}

var blockerKindHelp = map[string]string{
	BlockerMissingID:          "The legacy state holds no server id for an object, so its destination cannot be imported. Refresh the state with the source provider, or rerun with `-remote` to read the id back from the project with a GET.",
	BlockerUnresolvedSecret:   "A destination requires a sensitive value that the legacy state does not hold. Supply it from your own secret store; the utility will never invent one.",
	BlockerUnresolvedRef:      "One object references another by name and the destination needs its id. Adopt the referenced object in the same migration, or declare it before adopting the referencing one.",
	BlockerMissingPayload:     "A destination requires a JSON document (a flow, widget, style or template body) that the legacy state does not hold.",
	BlockerUnsupportedField:   "A populated legacy attribute has no destination in the target provider. Decide explicitly what should happen to that configuration before migrating.",
	BlockerUnknownAttribute:   "The legacy state holds an attribute this version of the utility does not know about, which means the state was written by a newer provider than the utility supports.",
	BlockerDuplicateAddress:   "Two legacy objects map onto the same destination address. Rename one of them in the legacy configuration first, so each destination has exactly one owner.",
	BlockerAmbiguousOwnership: "Ownership of a value cannot be decided from the legacy state alone.",
	BlockerInvalidValue:       "A legacy value does not fit the destination attribute, so carrying it over would change its meaning.",
}

func secretReport(m *Manifest) string {
	out := &strings.Builder{}
	section(out, "Secret requirements")
	line(out, "No secret value appears in this file or in any generated configuration. Each row names where the value")
	line(out, "lives in the legacy state snapshot so an operator can copy it into their own secret store.")
	blank(out)
	line(out, "`%s` contains the supplied Terraform snapshot and can contain these values in cleartext. Treat it as a", m.Rollback.StateBackup)
	line(out, "credential, store it where the team stores secrets, and never commit it.")
	blank(out)
	if len(m.Secrets) == 0 {
		line(out, "No destination requires a sensitive input.")
		blank(out)
		return out.String()
	}
	section2(out, "Required inputs")
	line(out, "| variable | destination | attribute | legacy state path | value present in state |")
	line(out, "| --- | --- | --- | --- | --- |")
	for _, secret := range m.Secrets {
		line(out, "| `var.%s` | `%s` | `%s` | `%s` | %s |", secret.Variable, secret.Address, secret.Attribute, secret.LegacyPath, yesNo(secret.Present))
	}
	blank(out)
	if m.ModuleAddress == "" {
		line(out, "Supply them from your root-module secret store, for example with `TF_VAR_<name>`. Do not write")
		line(out, "them into a committed `.tfvars` file.")
	} else {
		line(out, "`variables.tf` declares these inputs in `%s`. `TF_VAR_*` only sets root-module variables, so add", m.ModuleAddress)
		line(out, "matching sensitive root variables and pass each one through every existing module call in the path.")
		line(out, "Do not write their values into module blocks or a committed `.tfvars` file.")
	}
	blank(out)
	line(out, "Every supplied value must match the live credential exactly. A stale OIDC client secret or other")
	line(out, "replacement-forcing secret produces a replace action, and `verify-plan` rejects it.")
	blank(out)
	return out.String()
}

func rollbackReport(m *Manifest) string {
	out := &strings.Builder{}
	section(out, "Rollback")
	line(out, "This utility never rolls back, never removes state and never applies anything. The material below is")
	line(out, "what an operator needs to undo the migration by hand.")
	blank(out)
	line(out, "- input snapshot: `%s`", m.Rollback.StateBackup)
	line(out, "- restorable raw state: %s", yesNo(m.Rollback.Restorable))
	line(out, "- legacy address: `%s`", m.Rollback.LegacyAddress)
	line(out, "- source provider version to return to: `%s`", m.Rollback.SourceProvider)
	line(out, "- possible adoption-stage backend mutation: %s", m.Rollback.BackendMutation)
	blank(out)
	section2(out, "Steps")
	for i, step := range m.Rollback.Instructions {
		line(out, "%d. %s", i+1, step)
	}
	blank(out)
	line(out, "`%s` contains sensitive Terraform data in cleartext. Treat it as a credential.", m.Rollback.StateBackup)
	blank(out)
	line(out, "Neither stage creates or deletes a Descope object: stage 1 detaches state with `destroy = false`, and")
	line(out, "stage 2 imports existing objects. It can rehydrate required write-only secrets in place; restoring state")
	line(out, "does not restore those remote values, so rollback must restore or rotate them separately.")
	return out.String()
}

func moduleLabel(m *Manifest) string {
	if m.ModuleAddress == "" {
		return "root"
	}
	return m.ModuleAddress
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func section(out *strings.Builder, title string) {
	out.WriteString("# " + title + "\n\n")
}

func section2(out *strings.Builder, title string) {
	out.WriteString("## " + title + "\n\n")
}

func line(out *strings.Builder, format string, args ...any) {
	fmt.Fprintf(out, format+"\n", args...)
}

func blank(out *strings.Builder) {
	out.WriteString("\n")
}
