// Code generated by terragen. DO NOT EDIT.

package docs

var docsProject = map[string]string{
	"name": "",
	"tag": "",
	"project_settings": "",
	"authentication": "",
	"authorization": "",
	"attributes": "",
	"connectors": "",
	"applications": "",
	"jwt_templates": "",
	"styles": "",
	"flows": "",
}

var docsApplication = map[string]string{
	"oidc": "",
	"saml": "",
}

var docsOIDC = map[string]string{
	"id": "",
	"name": "",
	"description": "",
	"logo": "",
	"disabled": "",
	"login_page_url": "",
	"claims": "",
}

var docsSAML = map[string]string{
	"id": "",
	"name": "",
	"description": "",
	"logo": "",
	"disabled": "",
	"login_page_url": "",
	"dynamic_configuration": "",
	"manual_configuration": "",
	"acs_allowed_callback_urls": "",
	"subject_name_id_type": "",
	"subject_name_id_format": "",
	"default_relay_state": "",
	"attribute_mapping": "",
}

var docsAttributeMapping = map[string]string{
	"name": "",
	"value": "",
}

var docsDynamicConfiguration = map[string]string{
	"metadata_url": "",
}

var docsManualConfiguration = map[string]string{
	"acs_url": "",
	"entity_id": "",
	"certificate": "",
}

var docsAttributes = map[string]string{
	"tenant": "",
	"user": "",
}

var docsTenantAttribute = map[string]string{
	"name": "",
	"type": "",
	"select_options": "",
}

var docsUserAttribute = map[string]string{
	"name": "",
	"type": "",
	"select_options": "",
	"widget_authorization": "",
}

var docsUserAttributeWidgetAuthorization = map[string]string{
	"view_permissions": "",
	"edit_permissions": "",
}

var docsAuthentication = map[string]string{
	"otp": "",
	"magic_link": "",
	"enchanted_link": "",
	"embedded_link": "",
	"password": "",
	"oauth": "",
	"sso": "",
	"totp": "",
	"webauthn": "",
}

var docsEmbeddedLink = map[string]string{
	"enabled": "",
	"expiration_time": "",
	"expiration_time_unit": "",
}

var docsEnchantedLink = map[string]string{
	"enabled": "",
	"expiration_time": "",
	"expiration_time_unit": "",
	"redirect_url": "",
	"email_service": "",
}

var docsMagicLink = map[string]string{
	"enabled": "",
	"expiration_time": "",
	"expiration_time_unit": "",
	"redirect_url": "",
	"email_service": "",
	"text_service": "",
}

var docsOAuth = map[string]string{
	"disabled": "",
	"system": "",
	"custom": "",
}

var docsOAuthSystemProvider = map[string]string{
	"apple": "",
	"discord": "",
	"facebook": "",
	"github": "",
	"gitlab": "",
	"google": "",
	"linkedin": "",
	"microsoft": "",
	"slack": "",
}

var docsOAuthProvider = map[string]string{
	"disabled": "",
	"client_id": "",
	"client_secret": "",
	"provider_token_management": "",
	"prompts": "",
	"scopes": "",
	"merge_user_accounts": "",
	"description": "",
	"logo": "",
	"grant_type": "",
	"issuer": "",
	"authorization_endpoint": "",
	"token_endpoint": "",
	"user_info_endpoint": "",
	"jwks_endpoint": "",
	"claim_mapping": "",
}

var docsOTP = map[string]string{
	"enabled": "",
	"domain": "",
	"expiration_time": "",
	"expiration_time_unit": "",
	"email_service": "",
	"text_service": "",
	"voice_service": "",
}

var docsPassword = map[string]string{
	"enabled": "",
	"expiration": "",
	"expiration_weeks": "",
	"lock": "",
	"lock_attempts": "",
	"lowercase": "",
	"min_length": "",
	"non_alphanumeric": "",
	"number": "",
	"reuse": "",
	"reuse_amount": "",
	"uppercase": "",
	"email_service": "",
}

var docsSSO = map[string]string{
	"enabled": "",
	"merge_users": "",
}

var docsTOTP = map[string]string{
	"enabled": "",
}

var docsWebAuthn = map[string]string{
	"enabled": "",
	"top_level_domain": "",
}

var docsAuthorization = map[string]string{
	"roles": "",
	"permissions": "",
}

var docsPermission = map[string]string{
	"name": "",
	"description": "",
}

var docsRole = map[string]string{
	"name": "",
	"description": "",
	"permissions": "",
}

var docsAbuseIPDB = map[string]string{
	"name": "",
	"description": "",
	"api_key": "",
}

var docsAmplitude = map[string]string{
	"name": "",
	"description": "",
	"api_key": "",
	"server_url": "",
	"server_zone": "",
}

var docsAuditWebhook = map[string]string{
	"name": "",
	"description": "",
	"base_url": "",
	"authentication": "",
	"headers": "",
	"hmac_secret": "",
	"insecure": "",
	"audit_filters": "",
}

var docsAWSS3 = map[string]string{
	"name": "",
	"description": "",
	"access_key_id": "",
	"secret_access_key": "",
	"region": "",
	"bucket": "",
	"audit_enabled": "",
	"audit_filters": "",
	"troubleshoot_log_enabled": "",
}

var docsAWSTranslate = map[string]string{
	"name": "",
	"description": "",
	"access_key_id": "",
	"secret_access_key": "",
	"session_token": "",
	"region": "",
}

var docsClear = map[string]string{
	"name": "",
	"description": "",
	"project_id": "",
	"api_key": "",
}

var docsConnectors = map[string]string{
	"abuseipdb": "",
	"amplitude": "",
	"audit_webhook": "",
	"aws_s3": "",
	"aws_translate": "",
	"clear": "",
	"datadog": "",
	"devrev_grow": "",
	"docebo": "",
	"fingerprint": "",
	"fingerprint_descope": "",
	"forter": "",
	"google_cloud_translation": "",
	"hibp": "",
	"http": "",
	"http_static_ip": "",
	"hubspot": "",
	"intercom": "",
	"newrelic": "",
	"recaptcha": "",
	"recaptcha_enterprise": "",
	"rekognition": "",
	"salesforce": "",
	"segment": "",
	"sendgrid": "",
	"smtp": "",
	"sumologic": "",
	"telesign": "",
	"traceable": "",
	"twilio_core": "",
	"twilio_verify": "",
	"veriff": "",
}

var docsDatadog = map[string]string{
	"name": "",
	"description": "",
	"api_key": "",
	"site": "",
	"audit_enabled": "",
	"audit_filters": "",
	"troubleshoot_log_enabled": "",
}

var docsDevRevGrow = map[string]string{
	"name": "",
	"description": "",
	"api_key": "",
}

var docsDocebo = map[string]string{
	"name": "",
	"description": "",
	"base_url": "",
	"client_id": "",
	"client_secret": "",
	"username": "",
	"password": "",
}

var docsFingerprint = map[string]string{
	"name": "",
	"description": "",
	"public_api_key": "",
	"secret_api_key": "",
	"use_cloudflare_integration": "",
	"cloudflare_script_url": "",
	"cloudflare_endpoint_url": "",
}

var docsFingerprintDescope = map[string]string{
	"name": "",
	"description": "",
	"custom_domain": "",
}

var docsForter = map[string]string{
	"name": "",
	"description": "",
	"site_id": "",
	"secret_key": "",
	"overrides": "",
	"override_ip_address": "",
	"override_user_email": "",
}

var docsGoogleCloudTranslation = map[string]string{
	"name": "",
	"description": "",
	"project_id": "",
	"service_account_json": "",
}

var docsHIBP = map[string]string{
	"name": "",
	"description": "",
}

var docsHTTP = map[string]string{
	"name": "",
	"description": "",
	"base_url": "",
	"authentication": "",
	"headers": "",
	"hmac_secret": "",
	"insecure": "",
	"include_headers_in_context": "",
}

var docsHttpStaticIP = map[string]string{
	"name": "",
	"description": "",
	"base_url": "",
	"authentication": "",
	"headers": "",
	"hmac_secret": "",
	"insecure": "",
	"include_headers_in_context": "",
}

var docsHubSpot = map[string]string{
	"name": "",
	"description": "",
	"access_token": "",
	"base_url": "",
}

var docsIntercom = map[string]string{
	"name": "",
	"description": "",
	"token": "",
	"region": "",
}

var docsNewRelic = map[string]string{
	"name": "",
	"description": "",
	"api_key": "",
	"data_center": "",
	"audit_enabled": "",
	"audit_filters": "",
	"troubleshoot_log_enabled": "",
	"override_logs_prefix": "",
	"logs_prefix": "",
}

var docsRecaptcha = map[string]string{
	"name": "",
	"description": "",
	"site_key": "",
	"secret_key": "",
}

var docsRecaptchaEnterprise = map[string]string{
	"name": "",
	"description": "",
	"project_id": "",
	"site_key": "",
	"api_key": "",
	"override_assessment": "",
	"assessment_score": "",
}

var docsRekognition = map[string]string{
	"name": "",
	"description": "",
	"access_key_id": "",
	"secret_access_key": "",
	"collection_id": "",
}

var docsSalesforce = map[string]string{
	"name": "",
	"description": "",
	"base_url": "",
	"client_id": "",
	"client_secret": "",
	"version": "",
}

var docsSegment = map[string]string{
	"name": "",
	"description": "",
	"write_key": "",
	"host": "",
}

var docsSendGrid = map[string]string{
	"name": "",
	"description": "",
	"sender": "",
	"authentication": "",
}

var docsSendGridAuthField = map[string]string{
	"api_key": "",
}

var docsSenderField = map[string]string{
	"email": "",
	"name": "",
}

var docsServerField = map[string]string{
	"host": "",
	"port": "",
}

var docsHTTPAuthField = map[string]string{
	"bearer_token": "",
	"basic": "",
	"api_key": "",
}

var docsHTTPAuthBasicField = map[string]string{
	"username": "",
	"password": "",
}

var docsHTTPAuthAPIKeyField = map[string]string{
	"key": "",
	"token": "",
}

var docsSMTP = map[string]string{
	"name": "",
	"description": "",
	"sender": "",
	"server": "",
	"authentication": "",
}

var docsSMTPAuthField = map[string]string{
	"username": "",
	"password": "",
	"method": "",
}

var docsSumoLogic = map[string]string{
	"name": "",
	"description": "",
	"http_source_url": "",
	"audit_enabled": "",
	"audit_filters": "",
	"troubleshoot_log_enabled": "",
}

var docsTelesign = map[string]string{
	"name": "",
	"description": "",
	"customer_id": "",
	"api_key": "",
}

var docsTraceable = map[string]string{
	"name": "",
	"description": "",
	"secret_key": "",
	"eu_region": "",
}

var docsTwilioCore = map[string]string{
	"name": "",
	"description": "",
	"account_sid": "",
	"senders": "",
	"authentication": "",
}

var docsTwilioCoreSendersField = map[string]string{
	"sms": "",
	"voice": "",
}

var docsTwilioCoreSendersSMSField = map[string]string{
	"phone_number": "",
	"messaging_service_sid": "",
}

var docsTwilioCoreSendersVoiceField = map[string]string{
	"phone_number": "",
}

var docsTwilioAuthField = map[string]string{
	"auth_token": "",
	"api_key": "",
	"api_secret": "",
}

var docsTwilioVerify = map[string]string{
	"name": "",
	"description": "",
	"account_sid": "",
	"service_sid": "",
	"sender": "",
	"authentication": "",
}

var docsVeriff = map[string]string{
	"name": "",
	"description": "",
	"api_key": "",
	"secret_key": "",
	"base_url": "",
}

var docsFlow = map[string]string{
	"data": "",
}

var docsStyles = map[string]string{
	"data": "",
}

var docsJWTTemplate = map[string]string{
	"name": "",
	"description": "",
	"auth_schema": "",
	"conformance_issuer": "",
	"template": "",
	"type": "",
}

var docsJWTTemplates = map[string]string{
	"templates": "",
}

var docsSettings = map[string]string{
	"cookie_policy": "",
	"domain": "",
	"enable_inactivity": "",
	"inactivity_time": "",
	"refresh_token_expiration": "",
	"user_jwt_template": "",
	"access_key_jwt_template": "",
}

var docsEmailService = map[string]string{
	"connector": "",
	"templates": "",
}

var docsEmailTemplate = map[string]string{
	"active": "",
	"name": "",
	"subject": "",
	"html_body": "",
	"plain_text_body": "",
	"use_plain_text_body": "",
}

var docsTextService = map[string]string{
	"connector": "",
	"templates": "",
}

var docsTextTemplate = map[string]string{
	"active": "",
	"name": "",
	"body": "",
}

var docsVoiceService = map[string]string{
	"connector": "",
	"templates": "",
}

var docsVoiceTemplate = map[string]string{
	"active": "",
	"name": "",
	"body": "",
}
