name: Run Linter

description: Run Linter

runs:
  using: composite
  steps:
    - name: Setup Repo
      uses: ./.github/actions/ci/setup

    - name: Run Linter
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        version: v2.1.6
        args: --config=.github/actions/ci/lint/golangci.yml
