name: Run Linter

description: Run Linter

runs:
  using: composite
  steps:
    - name: Setup Repo
      uses: ./.github/actions/ci/setup

    - name: Run Linter
      uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1
      with:
        version: v1.64.5
        args: --config=.github/actions/ci/lint/golangci.yml
