name: Run Linter

description: Run Linter

runs:
  using: composite
  steps:
    - name: Setup Repo
      uses: ./.github/actions/ci/setup

    - name: Run Linter
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: v1.64.5
        args: --config=.github/actions/ci/lint/golangci.yml
