name: Run Linter

description: Run Linter

runs:
  using: composite
  steps:
    - name: Setup Repo
      uses: ./.github/actions/ci/setup

    - name: Run Linter
      uses: golangci/golangci-lint-action@e60da84bfae8c7920a47be973d75e15710aa8bd7 # v6.3.0
      with:
        version: v1.60.3
        args: --config=.github/actions/ci/lint/golangci.yml
