run:
  timeout: 3m

linters-settings:
  gofmt:
    simplify: false
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: defer
        arguments: [["loop", "return"]]
      - name: context-keys-type # Might cause slowness in lint
      - name: dot-imports
      - name: duplicated-imports
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf # Might cause slowness in lint
      - name: if-return
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: time-naming # Might cause slowness in lint
      - name: unconditional-recursion
      - name: unreachable-code
      # - name: unused-parameter # Temporarily disabled
      - name: var-declaration # Might cause slowness in lint
      - name: waitgroup-by-value

linters:
  disable-all: true
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godox
    - gofmt
    - goimports
    - gosimple
    # - govet # Temporarily disabled
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused

issues:
  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
