version: "2"

linters:
  default: none
  enable:
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - exhaustive
    - exptostd
    - forcetypeassert
    - godox
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
    - unused
    - wastedassign
    - whitespace
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000" # "At least one file in a package should have a package comment"
        - "-ST1003" # "Uppercase abbreviations in symbol names"
        - "-ST1020" # "Comment on exported function"
        - "-ST1021" # "Comment on exported type"
        - "-ST1022" # "Comment on exported constant"
        - "-QF1012" # "Use fmt.Fprintf instead of WriteString"
        - "-QF1008" # "Could remove embedded field from selector"
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: defer
          arguments:
            - - loop
              - return
        - name: context-keys-type
        - name: dot-imports
        - name: duplicated-imports
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: if-return
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unconditional-recursion
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: waitgroup-by-value
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: "parameter '(h|ctx)' seems to be unused.*"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
