// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/descope/terraform-provider-descope/internal/models/helpers/stringattr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var ClearAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"project_id": stringattr.Required(),
	"api_key":    stringattr.SecretRequired(),
}

// Model

type ClearModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	ProjectID stringattr.Type `tfsdk:"project_id"`
	APIKey    stringattr.Type `tfsdk:"api_key"`
}

func (m *ClearModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "clear"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *ClearModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *ClearModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.ProjectID, c, "projectId")
	stringattr.Get(m.APIKey, c, "apiKey")
	return c
}

func (m *ClearModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.ProjectID, c, "projectId")
	stringattr.Nil(&m.APIKey)
}

// Matching

func (m *ClearModel) GetName() stringattr.Type {
	return m.Name
}

func (m *ClearModel) GetID() stringattr.Type {
	return m.ID
}

func (m *ClearModel) SetID(id stringattr.Type) {
	m.ID = id
}
