// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var CybersixgillAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"client_id":     stringattr.Required(),
	"client_secret": stringattr.SecretRequired(),
}

// Model

type CybersixgillModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	ClientID     stringattr.Type `tfsdk:"client_id"`
	ClientSecret stringattr.Type `tfsdk:"client_secret"`
}

func (m *CybersixgillModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "cybersixgill"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *CybersixgillModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *CybersixgillModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.ClientID, c, "clientId")
	stringattr.Get(m.ClientSecret, c, "clientSecret")
	return c
}

func (m *CybersixgillModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.ClientID, c, "clientId")
	stringattr.Nil(&m.ClientSecret)
}

// Matching

func (m *CybersixgillModel) GetName() stringattr.Type {
	return m.Name
}

func (m *CybersixgillModel) GetID() stringattr.Type {
	return m.ID
}

func (m *CybersixgillModel) SetID(id stringattr.Type) {
	m.ID = id
}
