// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var MailjetAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"api_key":    stringattr.SecretRequired(),
	"secret_key": stringattr.SecretRequired(),
	"from_email": stringattr.Required(),
	"from_name":  stringattr.Default(""),
}

// Model

type MailjetModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	APIKey    stringattr.Type `tfsdk:"api_key"`
	SecretKey stringattr.Type `tfsdk:"secret_key"`
	FromEmail stringattr.Type `tfsdk:"from_email"`
	FromName  stringattr.Type `tfsdk:"from_name"`
}

func (m *MailjetModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "mail-jet"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *MailjetModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *MailjetModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.SecretKey, c, "secretKey")
	stringattr.Get(m.FromEmail, c, "fromEmail")
	stringattr.Get(m.FromName, c, "fromName")
	return c
}

func (m *MailjetModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.APIKey)
	stringattr.Nil(&m.SecretKey)
	stringattr.Set(&m.FromEmail, c, "fromEmail")
	stringattr.Set(&m.FromName, c, "fromName")
}

// Matching

func (m *MailjetModel) GetName() stringattr.Type {
	return m.Name
}

func (m *MailjetModel) GetID() stringattr.Type {
	return m.ID
}

func (m *MailjetModel) SetID(id stringattr.Type) {
	m.ID = id
}
