// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var PostmarkAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"server_apitoken":   stringattr.SecretRequired(),
	"message_stream_id": stringattr.Required(),
	"email_from":        stringattr.Required(),
}

// Model

type PostmarkModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	ServerAPIToken  stringattr.Type `tfsdk:"server_apitoken"`
	MessageStreamId stringattr.Type `tfsdk:"message_stream_id"`
	EmailFrom       stringattr.Type `tfsdk:"email_from"`
}

func (m *PostmarkModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "post-mark"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *PostmarkModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *PostmarkModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.ServerAPIToken, c, "serverAPIToken")
	stringattr.Get(m.MessageStreamId, c, "messageStreamId")
	stringattr.Get(m.EmailFrom, c, "emailFrom")
	return c
}

func (m *PostmarkModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.ServerAPIToken)
	stringattr.Set(&m.MessageStreamId, c, "messageStreamId")
	stringattr.Set(&m.EmailFrom, c, "emailFrom")
}

// Matching

func (m *PostmarkModel) GetName() stringattr.Type {
	return m.Name
}

func (m *PostmarkModel) GetID() stringattr.Type {
	return m.ID
}

func (m *PostmarkModel) SetID(id stringattr.Type) {
	m.ID = id
}
