// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var SqlAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"engine_name":   stringattr.Required(stringvalidator.OneOf("cockroach", "mariadb", "mysql", "oracle", "postgres", "redshift", "mssql")),
	"database_name": stringattr.Default(""),
	"service_name":  stringattr.Default(""),
	"host":          stringattr.Required(),
	"port":          floatattr.Default(0),
	"username":      stringattr.Required(),
	"password":      stringattr.SecretRequired(),
}

// Model

type SqlModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	EngineName   stringattr.Type `tfsdk:"engine_name"`
	DatabaseName stringattr.Type `tfsdk:"database_name"`
	ServiceName  stringattr.Type `tfsdk:"service_name"`
	Host         stringattr.Type `tfsdk:"host"`
	Port         floatattr.Type  `tfsdk:"port"`
	Username     stringattr.Type `tfsdk:"username"`
	Password     stringattr.Type `tfsdk:"password"`
}

func (m *SqlModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "sql"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SqlModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *SqlModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.EngineName, c, "engineName")
	stringattr.Get(m.DatabaseName, c, "databaseName")
	stringattr.Get(m.ServiceName, c, "serviceName")
	stringattr.Get(m.Host, c, "host")
	floatattr.Get(m.Port, c, "port")
	stringattr.Get(m.Username, c, "username")
	stringattr.Get(m.Password, c, "password")
	return c
}

func (m *SqlModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.EngineName, c, "engineName")
	stringattr.Set(&m.DatabaseName, c, "databaseName")
	stringattr.Set(&m.ServiceName, c, "serviceName")
	stringattr.Set(&m.Host, c, "host")
	floatattr.Set(&m.Port, c, "port")
	stringattr.Set(&m.Username, c, "username")
	stringattr.Nil(&m.Password)
}

// Matching

func (m *SqlModel) GetName() stringattr.Type {
	return m.Name
}

func (m *SqlModel) GetID() stringattr.Type {
	return m.ID
}

func (m *SqlModel) SetID(id stringattr.Type) {
	m.ID = id
}
