// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var ZerobounceAttributes = map[string]schema.Attribute{
	"id":          stringattr.IdentifierMatched(),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"api_key": stringattr.SecretRequired(),
	"region":  stringattr.Default("default", stringvalidator.OneOf("default", "us")),
}

// Model

type ZerobounceModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	APIKey stringattr.Type `tfsdk:"api_key"`
	Region stringattr.Type `tfsdk:"region"`
}

func (m *ZerobounceModel) Values(h *helpers.Handler) map[string]any {
	data := connectorValues(m.ID, m.Name, m.Description, h)
	data["type"] = "zerobounce"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *ZerobounceModel) SetValues(h *helpers.Handler, data map[string]any) {
	setConnectorValues(&m.ID, &m.Name, &m.Description, data, h)
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *ZerobounceModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.Region, c, "region")
	return c
}

func (m *ZerobounceModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.APIKey)
	stringattr.Set(&m.Region, c, "region")
}

// Matching

func (m *ZerobounceModel) GetName() stringattr.Type {
	return m.Name
}

func (m *ZerobounceModel) GetID() stringattr.Type {
	return m.ID
}

func (m *ZerobounceModel) SetID(id stringattr.Type) {
	m.ID = id
}
