// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_aws_end_user_messaging_connector is a standalone AWS End User Messaging connector with a server-assigned id.

var AWSEndUserMessagingConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a AWS End User Messaging connector and its configuration in a Descope project. Send OTP codes by SMS through AWS End User Messaging Notify, using AWS-managed numbers and preapproved templates.",
	Attributes:          AWSEndUserMessagingConnectorAttributes,
}

var AWSEndUserMessagingConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"aws_region":               stringattr.Required(),
	"auth_type":                stringattr.Default("credentials", stringvalidator.OneOf("", "credentials", "assumeRole")),
	"access_key_id":            stringattr.SecretOptional(),
	"secret_access_key":        stringattr.SecretOptional(),
	"role_arn":                 stringattr.Default(""),
	"external_id":              stringattr.Default(""),
	"notify_configuration_id":  stringattr.Required(),
	"default_template_id":      stringattr.Default(""),
	"template_code_variable":   stringattr.Default(""),
	"template_expiry_minutes":  floatattr.Default(0),
	"configuration_set_name":   stringattr.Default(""),
	"protect_configuration_id": stringattr.Default(""),
}

// Model

type AWSEndUserMessagingConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	AWSRegion              stringattr.Type `tfsdk:"aws_region"`
	AuthType               stringattr.Type `tfsdk:"auth_type"`
	AccessKeyID            stringattr.Type `tfsdk:"access_key_id"`
	SecretAccessKey        stringattr.Type `tfsdk:"secret_access_key"`
	RoleARN                stringattr.Type `tfsdk:"role_arn"`
	ExternalID             stringattr.Type `tfsdk:"external_id"`
	NotifyConfigurationID  stringattr.Type `tfsdk:"notify_configuration_id"`
	DefaultTemplateID      stringattr.Type `tfsdk:"default_template_id"`
	TemplateCodeVariable   stringattr.Type `tfsdk:"template_code_variable"`
	TemplateExpiryMinutes  floatattr.Type  `tfsdk:"template_expiry_minutes"`
	ConfigurationSetName   stringattr.Type `tfsdk:"configuration_set_name"`
	ProtectConfigurationID stringattr.Type `tfsdk:"protect_configuration_id"`
}

func (m *AWSEndUserMessagingConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "aws-end-user-messaging"
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *AWSEndUserMessagingConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *AWSEndUserMessagingConnectorModel) Validate(h *helpers.Handler) {
	if m.AccessKeyID.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "credentials" {
		h.Conflict("The access_key_id field can only be used when auth_type is set to 'credentials'")
	}
	if m.AccessKeyID.ValueString() == "" && !m.AccessKeyID.IsUnknown() && m.AuthType.ValueString() == "credentials" {
		h.Conflict("The access_key_id field is required when auth_type is set to 'credentials'")
	}
	if m.SecretAccessKey.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "credentials" {
		h.Conflict("The secret_access_key field can only be used when auth_type is set to 'credentials'")
	}
	if m.SecretAccessKey.ValueString() == "" && !m.SecretAccessKey.IsUnknown() && m.AuthType.ValueString() == "credentials" {
		h.Conflict("The secret_access_key field is required when auth_type is set to 'credentials'")
	}
	if m.RoleARN.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "assumeRole" {
		h.Conflict("The role_arn field can only be used when auth_type is set to 'assumeRole'")
	}
	if m.RoleARN.ValueString() == "" && !m.RoleARN.IsUnknown() && m.AuthType.ValueString() == "assumeRole" {
		h.Conflict("The role_arn field is required when auth_type is set to 'assumeRole'")
	}
	if m.ExternalID.ValueString() != "" && m.AuthType.ValueString() != "" && m.AuthType.ValueString() != "assumeRole" {
		h.Conflict("The external_id field can only be used when auth_type is set to 'assumeRole'")
	}
	if m.ExternalID.ValueString() == "" && !m.ExternalID.IsUnknown() && m.AuthType.ValueString() == "assumeRole" {
		h.Conflict("The external_id field is required when auth_type is set to 'assumeRole'")
	}
}

// Configuration

func (m *AWSEndUserMessagingConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.AWSRegion, c, "awsRegion")
	stringattr.Get(m.AuthType, c, "authType")
	stringattr.Get(m.AccessKeyID, c, "accessKeyId")
	stringattr.Get(m.SecretAccessKey, c, "secretAccessKey")
	stringattr.Get(m.RoleARN, c, "roleArn")
	stringattr.Get(m.ExternalID, c, "externalId")
	stringattr.Get(m.NotifyConfigurationID, c, "notifyConfigurationId")
	stringattr.Get(m.DefaultTemplateID, c, "defaultTemplateId")
	stringattr.Get(m.TemplateCodeVariable, c, "templateCodeVariable")
	floatattr.Get(m.TemplateExpiryMinutes, c, "templateExpiryMinutes")
	stringattr.Get(m.ConfigurationSetName, c, "configurationSetName")
	stringattr.Get(m.ProtectConfigurationID, c, "protectConfigurationId")
	return c
}

func (m *AWSEndUserMessagingConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.AWSRegion, c, "awsRegion")
	stringattr.Set(&m.AuthType, c, "authType")
	stringattr.SetSecret(&m.AccessKeyID, c, "accessKeyId", h)
	stringattr.SetSecret(&m.SecretAccessKey, c, "secretAccessKey", h)
	stringattr.Set(&m.RoleARN, c, "roleArn")
	stringattr.Set(&m.ExternalID, c, "externalId")
	stringattr.Set(&m.NotifyConfigurationID, c, "notifyConfigurationId")
	stringattr.Set(&m.DefaultTemplateID, c, "defaultTemplateId")
	stringattr.Set(&m.TemplateCodeVariable, c, "templateCodeVariable")
	floatattr.Set(&m.TemplateExpiryMinutes, c, "templateExpiryMinutes")
	stringattr.Set(&m.ConfigurationSetName, c, "configurationSetName")
	stringattr.Set(&m.ProtectConfigurationID, c, "protectConfigurationId")
}

func (m *AWSEndUserMessagingConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *AWSEndUserMessagingConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *AWSEndUserMessagingConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
