// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAWSEndUserMessagingConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "aws_end_user_messaging_connector")
	testacc.RunWithDestroyCheck(t, "descope_aws_end_user_messaging_connector",
		// create a new aws-end-user-messaging connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				aws_region = "vf4m23ly2"
				auth_type = "credentials"
				access_key_id = "ezzrllbqu22"
				secret_access_key = "xiyuadzk4w64hog"
				role_arn = null
				external_id = null
				notify_configuration_id = "qbugcwck4cxxforb3ewpn"
				default_template_id = "v75lq6uyd7j7uitsc"
				template_code_variable = "vd3rvsdovka47bddzoum"
				template_expiry_minutes = 21
				configuration_set_name = "guttmdz2j2twslbt37c4"
			`),
			Check: c.Check(map[string]any{
				"id":                      testacc.AttributeIsSet,
				"project_id":              testacc.AttributeIsSet,
				"name":                    c.Name,
				"description":             "",
				"aws_region":              "vf4m23ly2",
				"auth_type":               "credentials",
				"access_key_id":           "ezzrllbqu22",
				"secret_access_key":       "xiyuadzk4w64hog",
				"role_arn":                "",
				"external_id":             "",
				"notify_configuration_id": "qbugcwck4cxxforb3ewpn",
				"default_template_id":     "v75lq6uyd7j7uitsc",
				"template_code_variable":  "vd3rvsdovka47bddzoum",
				"template_expiry_minutes": 21,
				"configuration_set_name":  "guttmdz2j2twslbt37c4",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				aws_region = "mcbfgti5p"
				auth_type = "credentials"
				access_key_id = "an2mu73kjot"
				secret_access_key = "vzjnvlzyyvbdwad"
				role_arn = null
				external_id = null
				notify_configuration_id = "w6et4gg32h6xfxwhcvfof"
				default_template_id = "see2j2vg7e3mkkowm"
				template_code_variable = "qza44veuazb3fqh26how"
				template_expiry_minutes = 22
				configuration_set_name = "l65augp7jxxm5itoj3kr"
			`),
			Check: c.Check(map[string]any{
				"description":             "updated",
				"aws_region":              "mcbfgti5p",
				"auth_type":               "credentials",
				"access_key_id":           "an2mu73kjot",
				"secret_access_key":       "vzjnvlzyyvbdwad",
				"role_arn":                "",
				"external_id":             "",
				"notify_configuration_id": "w6et4gg32h6xfxwhcvfof",
				"default_template_id":     "see2j2vg7e3mkkowm",
				"template_code_variable":  "qza44veuazb3fqh26how",
				"template_expiry_minutes": 22,
				"configuration_set_name":  "l65augp7jxxm5itoj3kr",
			}),
		},
	)
}
