// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/models/attrs/listattr"
	"github.com/descope/terraform-provider-descope/internal/models/attrs/objattr"
	"github.com/descope/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_generic_sms_gateway_connector is a standalone Generic SMS gateway connector with a server-assigned id.

var GenericSMSGatewayConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Generic SMS gateway connector and its configuration in a Descope project. Send messages using a generic SMS gateway.",
	Attributes:          GenericSMSGatewayConnectorAttributes,
}

var GenericSMSGatewayConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"post_url":       stringattr.Required(),
	"sender":         stringattr.Default(""),
	"authentication": objattr.Default(HTTPAuthFieldDefault, HTTPAuthFieldAttributes, HTTPAuthFieldValidator),
	"headers":        listattr.Default[SecretObjectFieldModel](SecretObjectFieldAttributes, SecretObjectFieldValidator),
	"hmac_secret":    stringattr.SecretOptional(),
	"insecure":       boolattr.Default(false),
	"use_static_ips": boolattr.Default(false),
}

// Model

type GenericSMSGatewayConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	PostURL        stringattr.Type                       `tfsdk:"post_url"`
	Sender         stringattr.Type                       `tfsdk:"sender"`
	Authentication objattr.Type[HTTPAuthFieldModel]      `tfsdk:"authentication"`
	Headers        listattr.Type[SecretObjectFieldModel] `tfsdk:"headers"`
	HMACSecret     stringattr.Type                       `tfsdk:"hmac_secret"`
	Insecure       boolattr.Type                         `tfsdk:"insecure"`
	UseStaticIPs   boolattr.Type                         `tfsdk:"use_static_ips"`
}

func (m *GenericSMSGatewayConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "generic-sms-gateway"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *GenericSMSGatewayConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *GenericSMSGatewayConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.PostURL, c, "postUrl")
	stringattr.Get(m.Sender, c, "sender")
	objattr.Get(m.Authentication, c, "authentication", h)
	listattr.Get(m.Headers, c, "headers", h)
	stringattr.Get(m.HMACSecret, c, "hmacSecret")
	boolattr.Get(m.Insecure, c, "insecure")
	boolattr.Get(m.UseStaticIPs, c, "useStaticIps")
	return c
}

func (m *GenericSMSGatewayConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.PostURL, c, "postUrl")
	stringattr.Set(&m.Sender, c, "sender")
	objattr.Set(&m.Authentication, c, "authentication", h)
	setSecretObjectField(&m.Headers, c, "headers", h)
	stringattr.Nil(&m.HMACSecret)
	boolattr.Set(&m.Insecure, c, "insecure")
	boolattr.Set(&m.UseStaticIPs, c, "useStaticIps")
}

func (m *GenericSMSGatewayConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *GenericSMSGatewayConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *GenericSMSGatewayConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
