// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestMailjetConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "mailjet_connector")
	testacc.RunWithDestroyCheck(t, "descope_mailjet_connector",
		// create a new mailjet connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				sender_email = "pkik6p7rr"
				sender_name = "qquro4c7"
				api_key = "mhvece"
				secret_key = "wi4bhwt7a"
			`),
			Check: c.Check(map[string]any{
				"id":           testacc.AttributeIsSet,
				"project_id":   testacc.AttributeIsSet,
				"name":         c.Name,
				"description":  "",
				"sender_email": "pkik6p7rr",
				"sender_name":  "qquro4c7",
				"api_key":      "mhvece",
				"secret_key":   "wi4bhwt7a",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				sender_email = "macajtsxd"
				sender_name = "amlgf3lm"
				api_key = "24ynkg"
				secret_key = "ub2ewdlnz"
			`),
			Check: c.Check(map[string]any{
				"description":  "updated",
				"sender_email": "macajtsxd",
				"sender_name":  "amlgf3lm",
				"api_key":      "24ynkg",
				"secret_key":   "ub2ewdlnz",
			}),
		},
	)
}
