// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_mailjet_connector is a standalone Mailjet connector with a server-assigned id.

var MailjetConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Mailjet connector and its configuration in a Descope project. Send emails using Mailjet.",
	Attributes:          MailjetConnectorAttributes,
}

var MailjetConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"api_key":      stringattr.SecretRequired(),
	"secret_key":   stringattr.SecretRequired(),
	"sender_email": stringattr.Required(),
	"sender_name":  stringattr.Default(""),
}

// Model

type MailjetConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	APIKey      stringattr.Type `tfsdk:"api_key"`
	SecretKey   stringattr.Type `tfsdk:"secret_key"`
	SenderEmail stringattr.Type `tfsdk:"sender_email"`
	SenderName  stringattr.Type `tfsdk:"sender_name"`
}

func (m *MailjetConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "mail-jet"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *MailjetConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *MailjetConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.SecretKey, c, "secretKey")
	stringattr.Get(m.SenderEmail, c, "fromEmail")
	stringattr.Get(m.SenderName, c, "fromName")
	return c
}

func (m *MailjetConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.APIKey)
	stringattr.Nil(&m.SecretKey)
	stringattr.Set(&m.SenderEmail, c, "fromEmail")
	stringattr.Set(&m.SenderName, c, "fromName")
}

func (m *MailjetConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *MailjetConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *MailjetConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
