// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestMicrosoftSentinelConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "microsoft_sentinel_connector")
	testacc.RunWithDestroyCheck(t, "descope_microsoft_sentinel_connector",
		// create a new microsoft-sentinel connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				ingestion_endpoint = "vmdc5nqeneni7xakf"
				dcr_immutable_id = "kvqcclsw5fmqd3"
				stream_name = "Custom-DescopeAudit_CL"
				tenant_id = "vllrzvhy"
				client_id = "sgetgyvq"
				client_secret = "tjpxl7uy4wbb"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["kekpon4oj34w"] }]
				troubleshoot_log_enabled = false
				troubleshoot_stream_name = "Custom-DescopeTroubleshoot_CL"
				mask_pii = false
			`),
			Check: c.Check(map[string]any{
				"id":                       testacc.AttributeIsSet,
				"project_id":               testacc.AttributeIsSet,
				"name":                     c.Name,
				"description":              "",
				"disabled":                 false,
				"ingestion_endpoint":       "vmdc5nqeneni7xakf",
				"dcr_immutable_id":         "kvqcclsw5fmqd3",
				"stream_name":              "Custom-DescopeAudit_CL",
				"tenant_id":                "vllrzvhy",
				"client_id":                "sgetgyvq",
				"client_secret":            "tjpxl7uy4wbb",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"kekpon4oj34w"},
				"troubleshoot_log_enabled": false,
				"troubleshoot_stream_name": "Custom-DescopeTroubleshoot_CL",
				"mask_pii":                 false,
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				disabled = true
				ingestion_endpoint = "ukt545fiy7u63uh5d"
				dcr_immutable_id = "cu4wbytoiewyen"
				stream_name = "Custom-DescopeAudit_CL"
				tenant_id = "ag4mk5t3"
				client_id = "44l33qeq"
				client_secret = "hgw76gicp7vp"
				audit_enabled = true
				audit_filters = [{ key = "actions", operator = "includes", values = ["po4by43vyqpb"] }]
				troubleshoot_log_enabled = false
				troubleshoot_stream_name = "Custom-DescopeTroubleshoot_CL"
				mask_pii = true
			`),
			Check: c.Check(map[string]any{
				"description":              "updated",
				"disabled":                 true,
				"ingestion_endpoint":       "ukt545fiy7u63uh5d",
				"dcr_immutable_id":         "cu4wbytoiewyen",
				"stream_name":              "Custom-DescopeAudit_CL",
				"tenant_id":                "ag4mk5t3",
				"client_id":                "44l33qeq",
				"client_secret":            "hgw76gicp7vp",
				"audit_enabled":            true,
				"audit_filters.0.values":   []string{"po4by43vyqpb"},
				"troubleshoot_log_enabled": false,
				"troubleshoot_stream_name": "Custom-DescopeTroubleshoot_CL",
				"mask_pii":                 true,
			}),
		},
	)
}
