// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/listattr"
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_microsoft_sentinel_connector is a standalone Microsoft Sentinel connector with a server-assigned id.

var MicrosoftSentinelConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Microsoft Sentinel connector and its configuration in a Descope project. Stream audit events to Microsoft Sentinel through the Azure Monitor Logs Ingestion API. Requires a Log Analytics workspace with Microsoft Sentinel enabled and an Entra application with permission to publish to a data collection rule.",
	Attributes:          MicrosoftSentinelConnectorAttributes,
}

var MicrosoftSentinelConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"ingestion_endpoint": stringattr.Required(),
	"dcr_immutable_id":   stringattr.Required(),
	"stream_name":        stringattr.Required(),
	"tenant_id":          stringattr.Required(),
	"client_id":          stringattr.Required(),
	"client_secret":      stringattr.SecretRequired(),
	"audit_enabled":      boolattr.Default(true),
	"audit_filters":      listattr.Default[AuditFilterFieldModel](AuditFilterFieldAttributes),
	"mask_pii":           boolattr.Default(false),
}

// Model

type MicrosoftSentinelConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	IngestionEndpoint stringattr.Type                      `tfsdk:"ingestion_endpoint"`
	DcrImmutableId    stringattr.Type                      `tfsdk:"dcr_immutable_id"`
	StreamName        stringattr.Type                      `tfsdk:"stream_name"`
	TenantId          stringattr.Type                      `tfsdk:"tenant_id"`
	ClientID          stringattr.Type                      `tfsdk:"client_id"`
	ClientSecret      stringattr.Type                      `tfsdk:"client_secret"`
	AuditEnabled      boolattr.Type                        `tfsdk:"audit_enabled"`
	AuditFilters      listattr.Type[AuditFilterFieldModel] `tfsdk:"audit_filters"`
	MaskPII           boolattr.Type                        `tfsdk:"mask_pii"`
}

func (m *MicrosoftSentinelConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "microsoft-sentinel"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *MicrosoftSentinelConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *MicrosoftSentinelConnectorModel) Validate(h *helpers.Handler) {
	if !m.AuditFilters.IsEmpty() && !m.AuditEnabled.IsUnknown() && !m.AuditEnabled.IsNull() && !m.AuditEnabled.ValueBool() {
		h.Conflict("The audit_filters field cannot be used when audit_enabled isn't set to true")
	}
}

// Configuration

func (m *MicrosoftSentinelConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.IngestionEndpoint, c, "ingestionEndpoint")
	stringattr.Get(m.DcrImmutableId, c, "dcrImmutableId")
	stringattr.Get(m.StreamName, c, "streamName")
	stringattr.Get(m.TenantId, c, "tenantId")
	stringattr.Get(m.ClientID, c, "clientId")
	stringattr.Get(m.ClientSecret, c, "clientSecret")
	boolattr.Get(m.AuditEnabled, c, "auditEnabled")
	listattr.Get(m.AuditFilters, c, "auditFilters", h)
	boolattr.Get(m.MaskPII, c, "maskPII")
	return c
}

func (m *MicrosoftSentinelConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.IngestionEndpoint, c, "ingestionEndpoint")
	stringattr.Set(&m.DcrImmutableId, c, "dcrImmutableId")
	stringattr.Set(&m.StreamName, c, "streamName")
	stringattr.Set(&m.TenantId, c, "tenantId")
	stringattr.Set(&m.ClientID, c, "clientId")
	stringattr.SetSecret(&m.ClientSecret, c, "clientSecret", h)
	boolattr.Set(&m.AuditEnabled, c, "auditEnabled")
	listattr.Set(&m.AuditFilters, c, "auditFilters", h)
	boolattr.Set(&m.MaskPII, c, "maskPII")
}

func (m *MicrosoftSentinelConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *MicrosoftSentinelConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *MicrosoftSentinelConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
