// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/models/attrs/boolattr"
	"github.com/descope/terraform-provider-descope/internal/models/attrs/floatattr"
	"github.com/descope/terraform-provider-descope/internal/models/attrs/listattr"
	"github.com/descope/terraform-provider-descope/internal/models/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/models/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_snowflake_connector is a standalone Snowflake connector with a server-assigned id.

var SnowflakeConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Snowflake connector and its configuration in a Descope project. Stream authentication audit logs to your Snowflake data warehouse with the Snowflake connector.",
	Attributes:          SnowflakeConnectorAttributes,
}

var SnowflakeConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),
	"disabled":    boolattr.Default(false),

	"api_key":                    stringattr.SecretRequired(),
	"site":                       stringattr.Required(),
	"warehouse":                  stringattr.Required(),
	"database":                   stringattr.Required(),
	"schema":                     stringattr.Required(),
	"audit_table":                stringattr.Default("DESCOPE_AUDIT_LOGS"),
	"self_provision":             boolattr.Default(false),
	"audit_enabled":              boolattr.Default(true),
	"audit_filters":              listattr.Default[AuditFilterFieldModel](AuditFilterFieldAttributes),
	"min_flush_interval_minutes": floatattr.Default(15),
	"troubleshoot_log_enabled":   boolattr.Default(false),
	"mask_pii":                   boolattr.Default(false),
}

// Model

type SnowflakeConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`
	Disabled    boolattr.Type   `tfsdk:"disabled"`

	APIKey                  stringattr.Type                      `tfsdk:"api_key"`
	Site                    stringattr.Type                      `tfsdk:"site"`
	Warehouse               stringattr.Type                      `tfsdk:"warehouse"`
	Database                stringattr.Type                      `tfsdk:"database"`
	Schema                  stringattr.Type                      `tfsdk:"schema"`
	AuditTable              stringattr.Type                      `tfsdk:"audit_table"`
	SelfProvision           boolattr.Type                        `tfsdk:"self_provision"`
	AuditEnabled            boolattr.Type                        `tfsdk:"audit_enabled"`
	AuditFilters            listattr.Type[AuditFilterFieldModel] `tfsdk:"audit_filters"`
	MinFlushIntervalMinutes floatattr.Type                       `tfsdk:"min_flush_interval_minutes"`
	TroubleshootLogEnabled  boolattr.Type                        `tfsdk:"troubleshoot_log_enabled"`
	MaskPII                 boolattr.Type                        `tfsdk:"mask_pii"`
}

func (m *SnowflakeConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "snowflake"
	if m.Disabled.ValueBool() {
		data["status"] = "disabled"
	} else {
		data["status"] = "enabled"
	}
	m.Validate(h)
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *SnowflakeConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if s, ok := data["status"].(string); ok {
		m.Disabled = boolattr.Value(s == "disabled")
	} else {
		m.Disabled = boolattr.Value(false)
	}
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

func (m *SnowflakeConnectorModel) Validate(h *helpers.Handler) {
	if !m.AuditFilters.IsEmpty() && !m.AuditEnabled.IsNull() && !m.AuditEnabled.ValueBool() {
		h.Conflict("The audit_filters field cannot be used when audit_enabled isn't set to true")
	}
}

// Configuration

func (m *SnowflakeConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.Site, c, "site")
	stringattr.Get(m.Warehouse, c, "warehouse")
	stringattr.Get(m.Database, c, "database")
	stringattr.Get(m.Schema, c, "schema")
	stringattr.Get(m.AuditTable, c, "auditTable")
	boolattr.Get(m.SelfProvision, c, "selfProvision")
	boolattr.Get(m.AuditEnabled, c, "auditEnabled")
	listattr.Get(m.AuditFilters, c, "auditFilters", h)
	floatattr.Get(m.MinFlushIntervalMinutes, c, "minFlushIntervalMinutes")
	boolattr.Get(m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	boolattr.Get(m.MaskPII, c, "maskPII")
	return c
}

func (m *SnowflakeConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Nil(&m.APIKey)
	stringattr.Set(&m.Site, c, "site")
	stringattr.Set(&m.Warehouse, c, "warehouse")
	stringattr.Set(&m.Database, c, "database")
	stringattr.Set(&m.Schema, c, "schema")
	stringattr.Set(&m.AuditTable, c, "auditTable")
	boolattr.Set(&m.SelfProvision, c, "selfProvision")
	boolattr.Set(&m.AuditEnabled, c, "auditEnabled")
	listattr.Set(&m.AuditFilters, c, "auditFilters", h)
	floatattr.Set(&m.MinFlushIntervalMinutes, c, "minFlushIntervalMinutes")
	boolattr.Set(&m.TroubleshootLogEnabled, c, "troubleshootLogEnabled")
	boolattr.Set(&m.MaskPII, c, "maskPII")
}

func (m *SnowflakeConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *SnowflakeConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *SnowflakeConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
