// Code generated by terragen. DO NOT EDIT.

package connectors

import (
	"github.com/descope/terraform-provider-descope/internal/attrs/stringattr"
	"github.com/descope/terraform-provider-descope/internal/helpers"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// descope_vonage_connector is a standalone Vonage connector with a server-assigned id.

var VonageConnectorSchema = schema.Schema{
	MarkdownDescription: "Manages a Vonage connector and its configuration in a Descope project. Send text messages through Vonage.",
	Attributes:          VonageConnectorAttributes,
}

var VonageConnectorAttributes = map[string]schema.Attribute{
	"id":          stringattr.Identifier(),
	"project_id":  stringattr.Required(stringplanmodifier.RequiresReplace()),
	"name":        stringattr.Required(stringattr.StandardLenValidator),
	"description": stringattr.Default(""),

	"api_key":    stringattr.Required(),
	"api_secret": stringattr.SecretRequired(),
	"sender":     stringattr.Required(),
}

// Model

type VonageConnectorModel struct {
	ID          stringattr.Type `tfsdk:"id"`
	ProjectID   stringattr.Type `tfsdk:"project_id"`
	Name        stringattr.Type `tfsdk:"name"`
	Description stringattr.Type `tfsdk:"description"`

	APIKey    stringattr.Type `tfsdk:"api_key"`
	APISecret stringattr.Type `tfsdk:"api_secret"`
	Sender    stringattr.Type `tfsdk:"sender"`
}

func (m *VonageConnectorModel) Values(h *helpers.Handler) map[string]any {
	data := map[string]any{}
	stringattr.Get(m.Name, data, "name")
	stringattr.Get(m.Description, data, "description")
	data["type"] = "vonage"
	data["configuration"] = m.ConfigurationValues(h)
	return data
}

func (m *VonageConnectorModel) SetValues(h *helpers.Handler, data map[string]any) {
	stringattr.Set(&m.Name, data, "name")
	stringattr.Set(&m.Description, data, "description")
	if c, ok := data["configuration"].(map[string]any); ok {
		m.SetConfigurationValues(c, h)
	}
}

// Configuration

func (m *VonageConnectorModel) ConfigurationValues(h *helpers.Handler) map[string]any {
	c := map[string]any{}
	stringattr.Get(m.APIKey, c, "apiKey")
	stringattr.Get(m.APISecret, c, "apiSecret")
	stringattr.Get(m.Sender, c, "from")
	return c
}

func (m *VonageConnectorModel) SetConfigurationValues(c map[string]any, h *helpers.Handler) {
	stringattr.Set(&m.APIKey, c, "apiKey")
	stringattr.Nil(&m.APISecret)
	stringattr.Set(&m.Sender, c, "from")
}

func (m *VonageConnectorModel) GetID() stringattr.Type        { return m.ID }
func (m *VonageConnectorModel) SetID(id stringattr.Type)      { m.ID = id }
func (m *VonageConnectorModel) GetProjectID() stringattr.Type { return m.ProjectID }
