// Code generated by terragen. DO NOT EDIT.

package connectors_test

import (
	"testing"

	"github.com/descope/terraform-provider-descope/tools/testacc"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestVonageConnector(t *testing.T) {
	projectID := testacc.ProjectID(t)
	c := testacc.NewResource(t, "vonage_connector")
	testacc.RunWithDestroyCheck(t, "descope_vonage_connector",
		// create a new vonage connector
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				api_key = "mhvece"
				api_secret = "hgg666mus"
				sender = "owcx"
				application_id = "pwycpxayqxkgs"
				private_key = "6wzyztm5y5"
				from_phone_voice = "giw4ng3jcdb6cc"
			`),
			Check: c.Check(map[string]any{
				"id":               testacc.AttributeIsSet,
				"project_id":       testacc.AttributeIsSet,
				"name":             c.Name,
				"description":      "",
				"api_key":          "mhvece",
				"api_secret":       "hgg666mus",
				"sender":           "owcx",
				"application_id":   "pwycpxayqxkgs",
				"private_key":      "6wzyztm5y5",
				"from_phone_voice": "giw4ng3jcdb6cc",
			}),
		},
		// update the connector in place with changed field values
		resource.TestStep{
			Config: c.Config(`
				project_id = "` + projectID + `"
				description = "updated"
				api_key = "24ynkg"
				api_secret = "k6o5jhwwg"
				sender = "crbp"
				application_id = "4ickrrc2zofmr"
				private_key = "5zaotnwgqo"
				from_phone_voice = "cqqrmbdvote3ax"
			`),
			Check: c.Check(map[string]any{
				"description":      "updated",
				"api_key":          "24ynkg",
				"api_secret":       "k6o5jhwwg",
				"sender":           "crbp",
				"application_id":   "4ickrrc2zofmr",
				"private_key":      "5zaotnwgqo",
				"from_phone_voice": "cqqrmbdvote3ax",
			}),
		},
	)
}
